version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/threat_dashboard
    depends_on:
      - mongo
    volumes:
      - ./backend/data:/app/data   # <--- Mount data folder into container


  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo_data:
